USE [master]
GO

/****** Object:  Database [Admin]    Script Date: 19/11/2015 10:55:12 a.m. ******/
CREATE DATABASE [Admin]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Admin', FILENAME = N'D:\Data\Admin.mdf' , SIZE = 87040KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Admin_log', FILENAME = N'L:\Logs\Admin_log.ldf' , SIZE = 517184KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Admin] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Admin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Admin] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Admin] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Admin] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Admin] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Admin] SET ARITHABORT OFF 
GO

ALTER DATABASE [Admin] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Admin] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Admin] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Admin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Admin] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Admin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Admin] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Admin] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Admin] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Admin] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Admin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Admin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Admin] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Admin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Admin] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Admin] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Admin] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Admin] SET RECOVERY FULL 
GO

ALTER DATABASE [Admin] SET  MULTI_USER 
GO

ALTER DATABASE [Admin] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Admin] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Admin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Admin] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Admin] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Admin] SET  READ_WRITE 
GO

